### ISSUE TITLE
Leading zeros are missing in segment time

### ISSUE THREAD

**Issue by ImAciidz** [Balouxe/LiveSplit.RunExtractor#1]
![image](https://user-images.githubusercontent.com/62849155/199830933-be82e380-ab4a-44b7-9dbd-9daabe7747af.png)
00:01:17 is incorrectly displayed as 0:1:17, 00:13:08 as 0:13:8, etc.

**Comment by Balouxe** [comment]
I didn't think that was too much of an issue, because it pastes fine into LiveSplit. 
The main issue I had with adding the 0s is that i have to transform every time into strings and if you're scrolling between yours runs really quickly it can get laggy. I'll see what I can do, thanks!
