### ISSUE TITLE
Crashes with certain split files

### ISSUE THREAD

**Issue by ImAciidz** [Balouxe/LiveSplit.RunExtractor#2]
[splits_that_crash.zip](https://github.com/Balouxe/LiveSplit.RunExtractor/files/9933329/splits_that_crash.zip)

**Comment by Balouxe** [comment]
Thanks! I'll look into that

**Comment by Balouxe** [comment]
Issue was really easy to fix! It was basically crashing if the split name was empty.
I'll push the commit and will make a new realease when I'm done fixing your other issues
